## Press
1. [Ann Arbor bikeway clocks record-high 10,000-plus trips in July](https://www.mlive.com/news/ann-arbor/2023/08/ann-arbor-bikeway-clocks-record-high-10000-plus-trips-in-july.html), MLive, August 2023
1. ["Ann Arbor's new bikeways used by many, help grow bike ridership"](https://www.mlive.com/news/ann-arbor/2023/03/ann-arbors-new-bikeways-used-by-many-help-grow-bike-ridership.html), MLive, March 2023
1. ["Moving beyond Gold-Level: Ann Arbor cyclists want better biking infrastructure"](https://www.michigandaily.com/news/moving-beyond-gold-level-ann-arbor-cyclists-want-better-biking-infrastructure/), The Michigan Daily, March 2022
1. ["UM-Dearborn's Fred Feng lands NSF CAREER Award to advance bicycle safety research"](https://umdearborn.edu/news/articles/um-dearborns-fred-feng-lands-nsf-career-award-advance-bicycle-safety-research), University of Michigan-Dearborn, March 2022
1. ["Improving bicycling safety by developing a research framework for studying driver-bicyclist interactions"](https://midas.umich.edu/improving-bicycling-safety/), Michigan Institute for Data Science (MIDAS), February 2022
1. ["Where virtual reality is taking us next"](https://umdearborn.edu/news/articles/where-virtual-reality-taking-us-next), University of Michigan-Dearborn, January 2022
1. ["Bike safety research is going 'high-res' with this new technology"](https://umdearborn.edu/news/articles/bike-safety-research-going-high-res-new-technology), University of Michigan-Dearborn, July 2021
1. ["Making it safer to bike alongside autonomous cars"](http://umich.edu/~fredfeng/files/Making-it-safer-to-bike-alongside-autonomous-cars.pdf), University of Michigan Business Engagement Center, May 2020
1. ["Painted white lines are not cyclist-protecting forcefields, agree experts"](https://www.forbes.com/sites/carltonreid/2019/04/16/painted-white-lines-are-not-cyclist-protecting-forcefields-agree-experts/), Forbes, April 2019
1. ["Unlucky for bicyclists, every 13th passing motorist is looking elsewhere"](https://www.forbes.com/sites/carltonreid/2018/10/10/unlucky-for-bicyclists-every-13th-passing-motorist-is-looking-elsewhere/), Forbes, October 2018
