## Services

### Professional services

#### Professional organizations
- Scientific Committee, [International Cycling Safety Conference](http://www.cyclingsafety.net), 2020-present
- Member, [Transportation Research Board (TRB)](https://www.trb.org/) [Bicycle Transportation Committee](https://sites.google.com/view/anf20/), 2023-2025
- Program Committee, [AutoUI (International ACM Conference on Automotive User Interfaces)](https://www.auto-ui.org/), 2018, 2020, 2021, 2022

#### Reviewer
-   Accident Analysis & Prevention
-   Applied Ergonomics
-   Human Factors and Ergonomics (HFES) Annual Meeting
-   International Journal of Human-Computer Interaction
-   IEEE Transactions on Intelligent Transportation Systems
-   IEEE Transactions on Human-Machine Systems
-   IEEE Intelligent Transportation Systems Magazine
-   IEEE Access
-   International ACM Conference on Automotive User Interfaces (AutoUI)
-   International Cycling Safety Conference
-   Transportation Research Part C: Emerging Technologies
-   Transportation Research Part F: Traffic Psychology and Behaviour
-   Transportmetrica A: Transport Science
-   Transportation Research Board (TRB) Annual Meeting

#### Workshop organizer

- "Automated vehicles are pretty much here: How can human factors research help prepare drivers, lawmakers, educators, and the public?", [Automated Vehicle Symposium](www.automatedvehiclessymposium.org) 2017
- "Acquisition and maintenance of driving skills in the climate of driver support, driver assist, and automation systems", [Transportation Research Board Annual Meeting](http://www.trb.org/AnnualMeeting/) 2017

#### Other services
- **Webmaster**: [Surface Transportation Technical
Group](http://hfessttg.blogspot.com/), [Human Factors and Ergonomics Society](https://www.hfes.org/), 2016-2018

### Departmental services

#### Committees

- Member, IMSE Department Research Committee (2024-present)
- Member, IMSE Department Social Media Committee (2019-present)
- Member, IMSE Department PhD Qualifying Exam Committee (2019-present)
- Member, IMSE Department LEO Lecture Major Review Committee (2022)

#### Other services

- Faculty Secretary, IMSE Department (2019-2023)
- Department Liaison, [HUB for Teaching and Learning](https://umdearborn.edu/faculty-staff/hub-teaching-learning-resources) (2021-2021)

### College services

#### Committees

- Member, [CECS](https://umdearborn.edu/cecs) [Energy Systems Engineering](https://umdearborn.edu/cecs/departments/electrical-and-computer-engineering/graduate-programs/mse-energy-systems-engineering) Program Reform Committee (2021-2022)
- Member, [CECS](https://umdearborn.edu/cecs) College Prominence Committee (2022-present)
- Member, [CECS](https://umdearborn.edu/cecs) Online Education Strategic Planning Committee (2021-2022)
- Member, [CECS](https://umdearborn.edu/cecs) Faculty Research Committee (2020)

#### Other services

- Digital Ambassador, [CECS](https://umdearborn.edu/cecs) (2020-present)

### University services

#### Committees

- Member, UM-Dearborn Urban Futures Strategic Planning Committee (2022)
- Member, UM-Dearborn Housing and Transportation Committee (2023)

#### Other services

- Faculty Senator, [UM-Dearborn Faculty Senate](https://umdearborn.edu/falty-senate), 2022-2028
- Faculty Senate Council, [UM-Dearborn Faculty Senate](https://umdearborn.edu/falty-senate), 2023-2024
- Volunteer Assistant Coach, [University of Michigan Cycling Team](https://www.umcycling.org/) (club sports), 2017-2021

### Local community services

#### Membership

- Board of directors, [Walk Bike Washtenaw](https://www.wbwc.org/), 2020-2024
- Member, [Healthy Environments Action Team](https://www.healthydearborn.org/healthy-environments), [Healthy Dearborn Coalition](https://www.healthydearborn.org/), 2020-2021
- Member, [Dearborn Healthy Streets Project](https://www.healthydearborn.org/dearbornhealthystreets) Planning Team, 2021

#### Invited talk & panelist

- [Ann Arbor Bike Summit](https://www.eventbrite.com/e/bike-summit-2023-tickets-575020450647?), 2023